### PR TITLE
API endpoints for training details

### PR DESCRIPTION
**Pull request by irisanissija**

### CODE REVIEW

**Comment by irisanissija** [comment]
Added API endpoints for training details:
Training details have the name of the training, date and link to the online training (all required so far), as well as an ID as the primary key. They are not yet linked to an user.
The training details can only be retrieved/created when the user is authenticated.

**Review by stefanha — APPROVED** [review]
Looks good!

The opportunities and volunteers migrations could be dropped from this pull request since training_details doesn't depend on them and they are likely to conflict with other pull requests that add those missing migrations (I sent a PR that adds the same missing opportunities migration changes here: PR#35).

**Review by stefanha — APPROVED** [review]
Great, thanks!

**Review by Nolski — APPROVED** [review]

**Pull request merged**
